PFE_NoteShare/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('custom_account/', include('custom_account.urls')),
    path('custom_account/', include('django.contrib.auth.urls')),
    path('custom_account/', include('allauth.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('cart/', include('cart.urls')),
    path('chat/', include('chat.urls')),
    path("", include('admin_corporate.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls.static import static
from django.urls import path, re_path

from PFE_NoteShare import settings
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('make_payment/', views.make_payment, name='make_payment'),
]

dashboard/urls.py
from django.conf.urls.static import static
from django.urls import path, re_path

from PFE_NoteShare import settings
from . import views

app_name = 'dashboard'
urlpatterns = [
                  path('', views.index, name='index'),
                  path('profile/', views.profile, name='profile'),
                  path('documents/<int:document_id>/review/', views.add_review, name='add_review'),
                  path('file-manager/', views.file_manager, name='file_manager'),
                  path('delete-file/<str:document_id>/', views.delete_file, name='delete_file'),
                  path('download-file/<str:document_id>/', views.download_file, name='download_file'),
                  path('delete-purchase/<str:document_id>/', views.delete_purchase, name='delete_purchase'),
                  path('delete-school/<str:school_id>/', views.delete_school, name='delete_school'),
                  path('delete-review/<str:review_id>/', views.delete_review, name='delete_review'),
                  path('delete-doct/<str:doct_id>/', views.delete_doct, name='delete_doct'),
                  path('delete-profile/<str:user_id>/', views.delete_profile, name='delete_profile'),
                  path('delete-subject/<str:subject_id>/', views.delete_subject, name='delete_subject'),
                  path('upload-file/', views.upload_file, name='upload_file'),
                  path('add-school/', views.add_school, name='add_school'),
                  path('add-subject/', views.add_subject, name='add_subject'),
                  path('update-subject/<str:subject_id>/', views.update_subject, name='update_subject'),
                  path('add-doct/', views.add_doct, name='add_doct'),
                  path('save-info/<str:document_id>/', views.save_info, name='save_info'),
                  path('search/', views.search, name='search'),
                  path('wallet/', views.wallet, name='wallet'),
                  path('first_page_preview/<int:document_id>/', views.first_page_preview, name='first_page_preview'),
                  path('update_profile', views.update_profile, name="update-profile"),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from audioop import reverse

from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.html import format_html

from .cart import Cart
from dashboard.models import Document, Student, Transaction
from django.http import JsonResponse


def cart_summary(request):
    user = request.user.student
    cart = Cart(request)
    cart_docs = cart.get_docs()
    print(cart_docs)
    total = cart.cart_total()
    points = user.points_field
    context = {
        'segment': 'cart',
        'cart_docs': cart_docs,
        'total': total,
        'points': points

    }
    return render(request, 'cart/cart_summary.html', context)


def cart_add(request):
    cart = Cart(request)
    student = request.user.student
    if request.POST.get('action') == 'post':
        document_id = int(request.POST.get('document_id'))
        document = get_object_or_404(Document, id=document_id)
        if document not in student.purchased_documents.all():
            cart.add(document=document)
        # Get Cart Quantity
        cart_quantity = cart.__len__()

        # Return resonse
        response = JsonResponse({'qty': cart_quantity})
        messages.success(request,
                         "Added Succesfully To Cart!")
        return response


def cart_delete(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        # Get stuff
        document_id = int(request.POST.get('document_id'))
        document = get_object_or_404(Document, id=document_id)
        # Call delete Function in Cart
        cart.delete(document=document)

        response = JsonResponse({'document': document_id})
        # return redirect('cart_summary')
        messages.success(request, ("Item Deleted From Shopping Cart..."))
        return response


def make_payment(request):
    if request.method == 'POST':
        student = request.user.student
        cart = Cart(request)
        cart_docs = cart.get_docs()
        total = cart.cart_total()
        points = student.points_field
        if not cart_docs:
            messages.warning(request, 'Your cart is empty.')
            return redirect(request.META.get('HTTP_REFERER'))
        if total <= points:
            cost = 0
            for doc in cart_docs:
                if doc not in student.purchased_documents.all():
                    student.purchased_documents.add(doc)
                    cost += doc.cost
                    Transaction.objects.create(
                        user=student,
                        document=doc,
                        transaction_type='purchase',
                        amount=doc.cost
                    )
            student.points_field -= cost
            student.save()
            cart.clear()
            messages.success(request, 'Documents added to your library!')
            return redirect(request.META.get('HTTP_REFERER'))
        else:
            messages.error(request, 'You do not have enough points. Please buy more points.')
            return redirect(request.META.get('HTTP_REFERER'))

templates/cart/cart_summary.html
{% extends 'dashboard/layouts/base.html' %}
{% load static file_extension info_value %}

{% block extrastyle %}
    <style>
        .modal {
            z-index: 99999 !important;
        }
    </style>
{% endblock extrastyle %}

{% block content %}
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
        </symbol>
        <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
            <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
        </symbol>
        <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
            <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
        </symbol>
    </svg>
    <div class="container-fluid py-4 px-5">
        {#    Cart List  #}
        <div class="row">
            <div class="col-12">
                <div class="card border shadow-xs mb-4">
                    <div class="card-header border-bottom pb-0">
                        <div class="d-sm-flex align-items-center">
                            <div>
                                <h6 class="font-weight-semibold text-lg mb-0">Cart</h6>
                                <p class="text-sm"><strong>Total:</strong> {{ total }} pt</p>
                            </div>
                            <div class="ms-auto d-flex">
                                <button type="button" class="btn btn-sm btn-white me-2">
                                    View all
                                </button>
                                <button type="button"
                                        class="btn btn-sm btn-dark btn-icon d-flex align-items-center me-2"
                                        data-bs-toggle="modal" data-bs-target="#exampleModal">
                                    <span class="btn-inner--icon me-1">
                                          <i class="fa fa-solid fa-cash-register fs-6"></i>
                                    </span>
                                    <a type="button" class="btn-inner--text"
                                       style="color: white; text-decoration: none;"> Checkout</a>
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="card-body px-0 py-0">

                        <div class="table-responsive p-0">
                            {% if cart_docs %}
                                <table class="table align-items-center mb-0">
                                    <thead class="bg-gray-100">
                                    <tr>
                                        <th class="text-secondary text-xs font-weight-semibold opacity-7">Document</th>
                                        <th class="text-secondary text-xs font-weight-semibold opacity-7 ps-2">Cost
                                        </th>
                                        <th class="text-secondary opacity-7"></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for document in cart_docs %}
                                        <tr>
                                            <td>
                                                <div class="d-flex px-2 py-1">
                                                    <div class="d-flex align-items-center">
                                                        <img src="{% url 'dashboard:first_page_preview' document_id=document.id %}"
                                                             alt="First Page Preview" class="avatar avatar-2xl me-2">
                                                    </div>
                                                    <div class="d-flex flex-column justify-content-center ms-1">
                                                        <h6 class="mb-0 text-sm font-weight-semibold">{{ document.id|display_value }}</h6>
                                                    </div>
                                                </div>
                                            </td>
                                            <td class="align-middle">
                                                <span class="text-secondary text-sm font-weight-normal">{{ document.cost }} pt</span>
                                            </td>
                                            <td class="align-middle">
                                                <button title="Remove From Cart"
                                                        id="delete-document"
                                                        class="fa fa-solid fa-trash text-danger delete-document"
                                                        type="button"
                                                        data-index="{{ document.id }}"
                                                        style="background:none; border: none;">
                                                </button>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            {% else %}
                                <div class="border-top py-3 px-3 d-flex align-items-center justify-content-center">
                                    <p class="font-weight-semibold mb-3 mt-3 text-dark text-lg">No Files Found</p>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Checkout Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1"
             aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg modal-fullscreen-lg-down">
                <form method="post" action="{% url 'cart:make_payment' %}"
                      enctype="multipart/form-data" class="modal-content">
                    {% csrf_token %}
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Order Summary</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="table-responsive p-0">
                            <table class="table align-items-center mb-0">
                                <thead class="bg-gray-100">
                                <tr>
                                    <th class="text-secondary text-xs font-weight-semibold opacity-7">Document</th>
                                    <th class="text-secondary text-xs font-weight-semibold opacity-7 ps-2">Cost
                                    </th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for document in cart_docs %}
                                    <tr>
                                        <td>
                                            <div class="d-flex px-2 py-1">
                                                <div class="d-flex align-items-center">
                                                    <img src="{% url 'dashboard:first_page_preview' document_id=document.id %}"
                                                         alt="First Page Preview" class="avatar avatar-2xl me-2">
                                                </div>
                                                <div class="d-flex flex-column justify-content-center ms-1">
                                                    <h6 class="mb-0 text-sm font-weight-semibold">{{ document.id|display_value }}</h6>
                                                </div>
                                            </div>
                                        </td>
                                        <td class="align-middle">
                                            <span class="text-secondary text-sm font-weight-normal">{{ document.cost }} pt</span>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="border-top py-3 px-3 d-flex align-items-center">
                        <p class="font-weight-semibold mb-0 text-dark text-sm"><strong>Total:</strong> {{ total }} pt
                            <br>
                            <strong>Your Balance:</strong> {{ points }} pt
                        </p>

                        <div class="ms-auto">
                            <button type="submit" class="btn btn-sm btn-light btn-icon d-flex align-items-center me-2">
                                    <span class="btn-inner--icon me-1">
                                          <i class="fa fa-solid fa-credit-card fs-6"></i>
                                    </span>
                                <a type="button" class="btn-inner--text"
                                   style="color: black; text-decoration: none;"> Make Payment</a>
                            </button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
        {% include 'dashboard/includes/footer.html' %}
    </div>

{% endblock content %}
{% block extrascripts %}
    <script>
        $(document).on('click', '#delete-document', function (e) {
            e.preventDefault();

            $.ajax({
                type: 'POST',
                url: '{% url 'cart:cart_delete' %}',
                data: {
                    document_id: $(this).data('index'),
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    action: 'post'
                },
                success: function (json) {
                    console.log(json)
                    //document.getElementById("cart_quantity").textContent = json.qty
                    location.reload();
                },

                error: function (xhr, errmsg, err) {

                }


            });

        })
    </script>
{% endblock extrascripts %}