PFE_NoteShare/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('custom_account/', include('custom_account.urls')),
    path('custom_account/', include('django.contrib.auth.urls')),
    path('custom_account/', include('allauth.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('cart/', include('cart.urls')),
    path('chat/', include('chat.urls')),
    path("", include('admin_corporate.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls.static import static
from django.urls import path, re_path

from PFE_NoteShare import settings
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('make_payment/', views.make_payment, name='make_payment'),
]

custom_account/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import CustomPasswordResetView, CustomPasswordResetConfirmView, CustomPasswordChangeView

from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from custom_account.views import login_user, logout_user, register_user, complete_profile

app_name = 'account'
urlpatterns = [
    path('login', login_user, name="login"),
    path('logout', logout_user, name="logout"),
    path('register', register_user, name="register"),
    path('update_profile', complete_profile, name="complete-profile"),

    # Password Reset URLs with Custom Templates
    path('password-reset/', CustomPasswordResetView.as_view(template_name='registration/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         CustomPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
    path('password_change/', CustomPasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_reset_complete.html'), name='password_change_done'),
]

templates/landing/partials/about.html
{% load static %}
{% block about %}
 <!-- Start About -->
 <section class="section" id="about">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-10">
                <div class="text-center mb-5">
                    <h3 class="mb-3">Empowering Students to Learn Smarter with NoteShare</h3>
                    <p class="text-muted">
                        NoteShare is revolutionizing the way students access study materials. Our platform simplifies the process of buying and selling materials using a unique point system. With an AI-powered search engine, finding relevant study resources has never been easier. Say goodbye to complex transactions and hello to seamless learning with NoteShare.
                    </p>
                </div>
            </div>
        </div>
        <!-- end row -->

        <div class="row">
            <div class="col-lg-4 col-md-4">
                <div class="text-center p-4">
                    <div class="icons-xl mb-3">
                        <i class="uim uim-ruler"></i>
                    </div>

                    <h5>Study Materials</h5>
                    <p class="text-muted">At NoteShare, find an array of study materials covering various subjects. Whether it's notes, guides, or practice exams, discover what you need to succeed.</p>
                </div>
            </div>

            <div class="col-lg-4 col-md-4">
                <div class="text-center p-4">
                    <div class="icons-xl mb-3">
                        <i class="uim uim-repeat"></i>
                    </div>

                    <h5>Point System</h5>
                    <p class="text-muted">Utilize our innovative point system to buy and sell study materials hassle-free. Earn points by contributing materials or redeem them to access the resources you need.</p>
                </div>
            </div>

            <div class="col-lg-4 col-md-4">
                <div class="text-center p-4">
                    <div class="icons-xl mb-3">
                        <i class="uim uim-airplay"></i>
                    </div>

                    <h5>AI-Powered Search</h5>
                    <p class="text-muted">With our AI-powered search engine, discover relevant study materials tailored to your needs. Spend less time searching and more time learning with NoteShare.</p>
                </div>
            </div>
        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
</section>
<!-- end About -->
{% endblock about %}

templates/landing/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <title>NoteShare - Your Gateway To Collaborative Learning</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="Premium Bootstrap 5 Landing Page Template" />
    <meta name="keywords" content="bootstrap 5, premium, marketing, multipurpose" />
    <meta name="author" content="Themesdesign" />

    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon_NoteShare.png' %}" />

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css" />

    <!-- Material Icon -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/materialdesignicons.min.css' %}" />

    <!-- tinyslider -->
    <link rel="stylesheet" href="{% static 'css/tiny-slider.css' %}">

    <!-- Custom  sCss -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
</head>

<body data-bs-spy="scroll" data-bs-target=".navbar" data-bs-offset="58">

    {% block navclass %}
    {% endblock navclass %}

    {% block navbar %}
        {% include "landing/partials/navbar.html" %}
    {% endblock navbar %}

    {% block hero %}
    {% endblock hero %}

    {% block about %}
        {% include "landing/partials/about.html" %}
    {% endblock about %}

{#    {% block features %}#}
{#        {% include "landing/partials/features.html" %}#}
{#    {% endblock features %}#}
{#    #}
{#    {% block clients %}#}
{#        {% include "landing/partials/clients.html" %}#}
{#    {% endblock clients %}#}
{##}
{#    {% block cta %}#}
{#        {% include "landing/partials/cta.html" %}#}
{#    {% endblock cta %}#}
{##}
{#    {% block pricing %}#}
{#        {% include "landing/partials/pricing.html" %}#}
{#    {% endblock pricing %}#}
{##}
{#    {% block contact %}#}
{#        {% include "landing/partials/contact.html" %}#}
{#    {% endblock contact %}#}

{#    {% block footer %}#}
{#        {% include "landing/partials/footer.html" %}#}
{#    {% endblock footer %}#}
{##}
{#    {% block footer_alt %}#}
{#        {% include "landing/partials/footer_alt.html" %}#}
{#    {% endblock footer_alt %}#}

    {% block javascript %}
        {% include "landing/partials/javascript.html" %}
    {% endblock javascript %}

    {% block extra_js %}
    {% endblock extra_js %}


</body>
</html>

templates/landing/partials/clients.html
{% load static %}
{% block clients %}
    <!-- Start Clients -->
    <section class="section mt-5" id="clients">
        <div class="container">
            <div class="row pb-5 align-items-center">
                <div class="col-lg-4 col-md-4">
                    <div class="icons-lg mb-4">
                        <i class="uim uim-comment-message"></i>
                    </div>
                    <h3 class="mb-2">2,200<sup>+</sup></h3>
                    <h3 class="mb-4">Satisfied Clients</h3>
                    <p class="text-muted mb-sm-0 mb-5 pb-sm-0 pb-4">If several languages coalesce, the grammar of the resulting language is more simple and regular than that of the individual</p>
                </div>

                <div class="col-lg-8 col-md-8">
                    <div class="client-slider">
                        <div>
                            <div class="bg-light rounded p-4">
                                <p class="text-muted mb-4">" It will be as simple as Occidental; in fact, it will be Occidental. To an English person, it will seem like simplified, If several languages of the resulting language"</p>
                                <div class="pt-3">
                                    <div class="d-inline-block">
                                        <h5 class="font-16 mb-1">James Vazquez</h5>
                                        <span class="text-muted">- Peyso User</span>
                                    </div>
                                    <div class="text-muted d-inline-block float-end">
                                        <i class="mdi mdi-star text-warning"></i>
                                        <i class="mdi mdi-star text-warning"></i>
                                        <i class="mdi mdi-star text-warning"></i>
                                        <i class="mdi mdi-star text-warning"></i>
                                        <i class="mdi mdi-star text-warning"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div>
                            <div class="bg-light rounded p-4">
                                <p class="text-muted mb-4">" To achieve this, it would be necessary to have uniform grammar, pronunciation and more common words. If several languages of the resulting language."</p>

                                <div class="pt-3">
                                    <div class="d-inline-block">
                                        <h5 class="font-16 mb-1">Clara Searcy</h5>
                                        <span class="text-muted">- Peyso User</span>
                                    </div>
                                    <div class="text-muted d-inline-block float-end">
                                        <i class="mdi mdi-star text-warning"></i>
                                        <i class="mdi mdi-star text-warning"></i>
                                        <i class="mdi mdi-star text-warning"></i>
                                        <i class="mdi mdi-star text-warning"></i>
                                        <i class="mdi mdi-star"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div>
                            <div class="bg-light rounded p-4">
                                <p class="text-muted mb-4">
                                    " If several It will be as simple as Occidental; it will be Occidental. To an English person, it will seem like simplified, If several languages of the resulting language "
                                </p>
                                <div class="pt-3">
                                    <div class="d-inline-block">
                                        <h5 class="font-16 mb-1">Alfredo Williams</h5>
                                        <span class="text-muted">- Peyso User</span>
                                    </div>
                                    <div class="text-muted d-inline-block float-end">
                                        <i class="mdi mdi-star text-warning"></i>
                                        <i class="mdi mdi-star text-warning"></i>
                                        <i class="mdi mdi-star text-warning"></i>
                                        <i class="mdi mdi-star text-warning"></i>
                                        <i class="mdi mdi-star"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end row -->

            <!-- start brand logo -->
            <div class="row mt-5">
                <div class="col-lg-3 col-sm-3">
                    <div class="client-images">
                        <img src="{% static 'images/clients/1.png' %}" alt="client-img" class="mx-auto img-fluid d-block" />
                    </div>
                </div>
                <div class="col-lg-3 col-sm-3">
                    <div class="client-images">
                        <img src="{% static 'images/clients/3.png' %}" alt="client-img" class="mx-auto img-fluid d-block" />
                    </div>
                </div>
                <div class="col-lg-3 col-sm-3">
                    <div class="client-images">
                        <img src="{% static 'images/clients/4.png' %}" alt="client-img" class="mx-auto img-fluid d-block" />
                    </div>
                </div>
                <div class="col-lg-3 col-sm-3">
                    <div class="client-images">
                        <img src="{% static 'images/clients/6.png' %}" alt="client-img" class="mx-auto img-fluid d-block" />
                    </div>
                </div>
            </div>
            <!-- end row -->
        </div>
        <!-- end container -->
    </section>
    <!-- End Clients -->
{% endblock clients %}

templates/landing/partials/contact.html
{% load static %}
{% block contact %}
   <!-- Start contact -->
   <section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="card contact-section-card mb-0">
                    <div class="card-body p-md-5">
                        <div class="text-center title mb-5">
                            <p class="text-muted text-uppercase fw-normal mb-2">Contact</p>
                            <h3 class="mb-3">Have any Questions ?</h3>
                            <div class="title-icon position-relative">
                                <div class="position-relative">
                                    <i class="uim uim-arrow-circle-down"></i>
                                </div>
                            </div>
                        </div>

                        <!-- start form -->
                        <form method="post" name="myForm" onsubmit="return validateForm()" href="javascript: void(0);">
                            <p id="error-msg"></p>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="mb-3">
                                        <label class="form-label" for="name">Name</label>
                                        <input name="name" id="name" type="text" class="form-control" placeholder="Enter your name..." />
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="mb-3">
                                        <label class="form-label" for="email">Email address</label>
                                        <input name="email" id="email" type="email" class="form-control" placeholder="Enter your email..." />
                                    </div>
                                </div>
                            </div>
                            <!-- end row -->

                            <div class="mb-3">
                                <label class="form-label" for="subject">Subject</label>
                                <input name="subject" id="subject" type="text" class="form-control" placeholder="Enter Subject..." />
                            </div>

                            <div class="mb-3">
                                <label class="form-label" for="comments">Message</label>
                                <textarea name="comments" id="comments" rows="3" class="form-control" placeholder="Enter your message..."></textarea>
                            </div>

                            <div class="text-end">
                                <input type="submit" id="submit" name="send" class="submitBnt btn btn-primary" value="Send message" />

                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
</section>
<!-- end contact -->
{% endblock contact %}

templates/landing/partials/cta.html
{% load static %}
{% block cta %}
 <!-- Start cta section -->
 <section class="py-5 bg-primary">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-9">
                <div class="text-white-50">
                    <h3 class="text-white">Build your dream website today</h3>
                    <p class="mb-0 fs-6">If several languages coalesce, the grammar of the resulting</p>
                </div>
            </div>

            <div class="col-md-3">
                <div class="mt-4 mt-md-0 text-md-end">
                    <a href="#" class="btn btn-info">Get Started</a>
                </div>
            </div>
        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
</section>
<!-- End cta section -->

{% endblock cta %}

templates/landing/partials/features.html
{% load static %}
{% block features %}
<!-- Start Features -->
<section class="section bg-light" id="features">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="text-center title mb-5">
                    <p class="text-muted text-uppercase fw-normal mb-2">Features</p>
                    <h3 class="mb-3">Key features of the product</h3>
                    <div class="title-icon position-relative">
                        <div class="position-relative">
                            <i class="uim uim-arrow-circle-down"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- end row -->

        <div class="row align-items-center">
            <div class="col-lg-5 order-2 order-lg-1">
                <div class="mt-4 mt-lg-0">
                    <h4>Improve your Marketing business</h4>
                    <p class="text-muted mt-3">If several languages coalesce, the grammar of the resulting language is more regular.</p>

                    <div>
                        <p class="mb-2 text-muted">
                            <span class="uim-icon-info me-2 align-middle"><i class="uim uim-check-circle"></i></span>Donec vitae sapien ut
                        </p>
                        <p class="mb-2 text-muted">
                            <span class="uim-icon-info me-2 align-middle"><i class="uim uim-check-circle"></i></span>In enim justo, rhoncus imperdiet
                        </p>
                        <p class="text-muted">
                            <span class="uim-icon-info me-2 align-middle"><i class="uim uim-check-circle"></i></span>Maecenas nec odio et
                        </p>
                    </div>
                    <div class="mt-4">
                        <a href="#" class="text-primary">Learn more..</a>
                    </div>
                </div>
            </div>

            <div class="col-lg-6 ms-lg-auto col-sm-8 order-1 order-lg-2">
                <div>
                    <img src="{% static 'images/features/img-1.jpg' %}" alt="" class="img-fluid mx-auto d-block" />
                </div>
            </div>
        </div>
        <!-- end row -->

        <hr class="my-5" />

        <div class="row align-items-center">
            <div class="col-lg-6 col-sm-8">
                <div class="features-img mt-4">
                    <img src="{% static 'images/features/img-2.jpg' %}" alt="" class="img-fluid mx-auto d-block img-thumbnail" />
                </div>
            </div>

            <div class="col-lg-5 ms-lg-auto">
                <div class="mt-5 mt-lg-4">
                    <h4>Improve your Marketing performance</h4>
                    <p class="text-muted mb-2 mt-3">It will be as simple as in fact, it will be Occidental. To an English person, it will seem like simplified</p>
                    <p class="text-muted">Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur velit</p>
                    <div class="mt-4">
                        <a href="#" class="text-primary">Learn more..</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
</section>
<!-- End Features -->
{% endblock features %}

templates/landing/partials/footer.html
{% load static %}
{% block footer %}
 <!-- start footer -->
 <footer class="footer bg-dark text-white-50">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <a href="#" class="d-block mb-3">
                    <img src="{% static 'images/logo-light.png' %}" alt="" height="20" />
                </a>
                <p>Bootstrap 5 Landing Page Template</p>
            </div>

            <div class="col-lg-2 col-sm-6">
                <div class="mt-4 mt-lg-0">
                    <h5 class="mb-4 font-18 text-white">Links</h5>
                    <ul class="list-unstyled footer-list-menu">
                        <li><a href="#">Home</a></li>
                        <li><a href="#">About us</a></li>
                        <li><a href="#">Careers</a></li>
                        <li><a href="#">Contact us</a></li>
                    </ul>
                </div>
            </div>

            <div class="col-lg-3 col-sm-6">
                <div class="mt-4 mt-lg-0">
                    <h5 class="mb-4 font-18 text-white">Resources</h5>
                    <ul class="list-unstyled footer-list-menu">
                        <li><a href="#">Help Center</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="#">Terms & Conditions</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="mt-4 mt-lg-0">
                    <h5 class="mb-4 font-18 text-white">Social</h5>
                    <ul class="list-inline social-icons-list">
                        <li class="list-inline-item">
                            <a href="#"><i class="mdi mdi-facebook"></i></a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#"><i class="mdi mdi-twitter"></i></a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#"><i class="mdi mdi-linkedin"></i></a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#"><i class="mdi mdi-google-plus"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
</footer>
<!-- end footer -->
{% endblock footer %}

templates/landing/partials/footer_alt.html
{% load static %}

{% block footer_alt %}
<!-- Start footer-alt -->
<section class="footer-alt py-3">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="text-center text-white-50">
                    <p class="mb-0">
                        <script>document.write(new Date().getFullYear())</script> © Peyso. Create by Themesdesign
                    </p>
                </div>
            </div>
        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
</section>
<!-- end footer-alt -->
{% endblock footer_alt %}

templates/landing/partials/javascript.html
{% load static %}
{% block javascript %}

    <!-- Javascript -->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    <!-- unicons -->
    <script src="https://unicons.iconscout.com/release/v2.1.11/script/monochrome/bundle.js"></script>


    <!-- testi-slider -->
    <script src="{% static 'js/tiny-slider.js' %}"></script>

    <!-- app js -->
    <script src="{% static 'js/app.js' %}"></script>
{% endblock javascript %}

templates/landing/partials/navbar.html
{% load static %}
{% block navbar %}
 <!--Navbar Start-->

    <div class="container">
        <a class="navbar-brand logo" href="#">
            <img src="{% static 'images/logo_NotesShare.png' %}" alt="" class="logo-light" height="20" />
{#            <img src="{% static 'images/logo-light.png' %}" alt="" class="logo-light" height="20" />#}
            <img src="{% static 'images/logo_NotesShare_dark_1.png' %}" alt="" class="logo-dark" height="20" />
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0" id="navbar-navlist">
                <li class="nav-item">
                    <a href="#home" class="nav-link" id="scrollElement">Home</a>
                </li>
                <li class="nav-item">
                    <a href="#about" class="nav-link">About</a>
                </li>
{#                <li class="nav-item">#}
{#                    <a href="#features" class="nav-link">Features</a>#}
{#                </li>#}
{#                <li class="nav-item">#}
{#                    <a href="#clients" class="nav-link">Clients</a>#}
{#                </li>#}
{#                <li class="nav-item">#}
{#                    <a href="#pricing" class="nav-link">Plans</a>#}
{#                </li>#}
{#                <li class="nav-item">#}
{#                    <a href="#contact" class="nav-link">Contact</a>#}
{#                </li>#}
            </ul>
            <a href="{% url 'account:login' %}" class="btn btn-light btn-sm navbar-btn me-2">Login</a>
            <a href="{% url 'account:register' %}" class="btn btn-info btn-sm navbar-btn my-lg-0 my-2">Sign Up<i class="mdi mdi-arrow-right ms-1"></i></a>

        </div>
    </div>
</nav>
<!-- Navbar End -->
{% endblock navbar %}